### ISSUE TITLE
yml files don't seem to correct 

### ISSUE THREAD

**Issue by amin-sagar** [HaotianZhangAI4Science/Delete#1]
Hello.
Thanks for this awesome work.
I tried to create an environment following the instructions but it doesn't work.
I looked at the yml files and they don't seem to be correct.
They seem to have the help content of conda env.
It would be great if you could share the environment requirements.
Thanks.
Amin.

**Comment by HaotianZhangAI4Science** [comment]
Sorry to response late, I have uploaded a conda-pack environment. If it does not work for you, please contact me again!

**Comment by amin-sagar** [comment]
Thanks @HaotianZhangAI4Science .
I tried with the second approach and I get this error for the test case.
```
(delete) amin@BTX-CC1:~/Work/test_delete/Delete$ python -u Delete.py --surf_path ./example/adrb1/adrb_pocket_8.0.ply --frag_path ./example/adrb1/2VT4_frag.sdf --check_point /home/amin/Downloads/delete.pt --outdir ../outputs --suboutdir adrb1
/home/amin/mambaforge/envs/delete/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Num of parameters is 37.06M
Traceback (most recent call last):
  File "Delete.py", line 157, in <module>
    data = surfdata_prepare(args.surf_path, args.frag_path)
  File "Delete.py", line 73, in surfdata_prepare
    ligand_dict = parse_rdmol(keep_frag_mol)
  File "/home/amin/Work/test_delete/Delete/utils/protein_ligand.py", line 300, in parse_rdmol
    factory = ChemicalFeatures.BuildFeatureFactory(fdefName)
OSError: File: /home/conda/feedstock_root/build_artifacts/rdkit_1660289026408/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/share/RDKit/Data/BaseFeatures.fdef could not be opened.
```
I would be really grateful for any suggestions.
Best,
Amin.

**Comment by HaotianZhangAI4Science** [comment]
That's because the rdkit cannot find the BaseFeatures.fdef file. You can directly specify this file path in the code. 
fdefName = 'BaseFeature.fdef path'
factory = ChemicalFeatures.BuildFeatureFactory(fdefName)

**Comment by amin-sagar** [comment]
Thanks @HaotianZhangAI4Science .
That solved the problem.
Best,
Amin.
