### ISSUE TITLE
small issue and GPU environment question

### ISSUE THREAD

**Issue by qoeogns09** [HaotianZhangAI4Science/Delete#2]
Hi, I'm daehun Bae. Thank you for sharing your interesting study.

When I implement your code, there is some small issue.
https://github.com/HaotianZhangAI4Science/Delete/blob/122791b24144c2b391a45ab59715f0ac53ab5644/delete_train.py#L87
I think in delete_train.py line 87, 'collate_exclude_keys' is removed.

Also, I have question about your environment.
Could you please give me about your GPU environment information?

Thank you.

**Comment by HaotianZhangAI4Science** [comment]
Dear Daehun Bae:
    Thanks for your reporting! Yes, the ligand_nbh_list is mistakenly removed, you can modify it as 
    collate_exclude_keys = ['ligand_nbh_list']

For the GPU environment. I run the code on the RTX 3090, with CUDA 11.3. Do you have some virtual environment problems? Try to conda unpack the provided environment, please. If you want to create one from scratch, the harshest part is to install the torch, torch_geometric and its utils, as well as the rdkit. I recommend you install them through the conda to automatically solve the possible incompatibility according to your local GPU environment.

**Comment by qoeogns09** [comment]
Thank you for response.

I have some problem in "delete_train" code. When I try your train code on crossdocked dataset, it shows "CUDA out of memory" in my server. I run the code on the RTX4090.

**Comment by HaotianZhangAI4Science** [comment]
I think the solution is to reduce the batch_size, try it!
