### ISSUE TITLE
masking part question

### ISSUE THREAD

**Issue by qoeogns09** [HaotianZhangAI4Science/Delete#3]
Hi. Thank you for sharing your interesting study.

I think that there exist reverse mistake. Fragment masking part should be change to bold code.
Which one is right? Colud you please check about it?

https://github.com/HaotianZhangAI4Science/Delete/blob/122791b24144c2b391a45ab59715f0ac53ab5644/utils/transforms.py#L542C1-L551C58

  if masked_frag is not None:
      masked_id = mol.GetSubstructMatch(masked_frag)
      context_id = list(set(list(range(num_atoms))) - set(masked_id))
      context_idx = torch.LongTensor(masked_id) **# It should be torch.LongTensor(context_id)**
      masked_idx = torch.LongTensor(context_id) **# It should be torch.LongTensor(masked_id)**
  else:
      context_id = mol.GetSubstructMatch(kept_frag)
      masked_id = list(set(list(range(num_atoms))) - set(context_id))
      context_idx = torch.LongTensor(masked_id)
      masked_idx = torch.LongTensor(context_id)

**Comment by HaotianZhangAI4Science** [comment]
Sorry to respond late. I just saw it.
The kept_frag means the fragment we want to reproduce, so the original version is right. I admit that the namespace is quite wired. I will change them in the next version, thanks for your report.
